using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using PdfEditor.Core;

namespace PdfEditor.Tests.Golden;

/// <summary>
/// The golden-file regression suite (issue #53).
/// <para>
/// Each corpus document is run through every real export operation and the result is projected to
/// a stable, readable summary (<see cref="GoldenProjection"/>) which is compared against a
/// recording committed under <c>Golden/goldens/</c>. Any change to how the engine rewrites a
/// document — a dropped <c>/ExtGState</c>, a lost <c>/ToUnicode</c>, a form XObject that stopped
/// being nested, a page that gained a validator finding — shows up as a diff on a reviewable text
/// file rather than as a subtly wrong PDF nobody opens.
/// </para>
/// <para>
/// The recordings are never regenerated by a failing run; see <see cref="GoldenFile"/>.
/// </para>
/// </summary>
public class GoldenRegressionTests
{
    public static TheoryData<string> CorpusNames()
    {
        var data = new TheoryData<string>();
        foreach (var doc in GoldenCorpus.Documents) data.Add(doc.Name);
        return data;
    }

    private static GoldenPdfs.GoldenDoc Doc(string name) =>
        GoldenCorpus.Documents.Single(d => d.Name == name);

    /// <summary>
    /// The suite proper: project the document, project the result of every operation over it, and
    /// hold the whole lot against the recording.
    /// </summary>
    [Theory]
    [MemberData(nameof(CorpusNames))]
    public void Corpus_MatchesRecordedGolden(string name)
    {
        var doc = Doc(name);
        var projection = new StringBuilder()
            .Append("# ").Append(doc.Name).Append('\n')
            .Append("# ").Append(doc.Description).Append('\n')
            .Append("== source ==\n")
            .Append(GoldenProjection.Describe(doc.Bytes));

        foreach (var (operation, run) in GoldenCorpus.Operations)
            projection.Append(GoldenProjection.DescribeOperation(operation, () => run(doc.Bytes)));

        string? failure = GoldenFile.Compare(doc.Name, projection.ToString());
        Assert.True(failure is null, failure);
    }

    /// <summary>
    /// The validator as oracle: whatever an operation does to a <em>well-formed</em> corpus
    /// document, the bytes it hands back must still be a document a strict consumer accepts. This
    /// is the check that does not need a recording to be useful — it would catch a brand-new
    /// writer bug on a brand-new fixture.
    /// </summary>
    [Theory]
    [MemberData(nameof(CorpusNames))]
    public void Operations_OverWellFormedCorpus_ProduceValidOutput(string name)
    {
        var doc = Doc(name);
        if (!doc.WellFormed) return;

        // The source fixture itself must be clean, or the operation results prove nothing.
        var source = ExportValidator.Validate(doc.Bytes);
        Assert.True(source.IsValid,
            $"Corpus fixture '{doc.Name}' is marked well-formed but does not validate:"
            + Environment.NewLine + source.ToLogText());

        var failures = new StringBuilder();
        foreach (var (operation, run) in GoldenCorpus.Operations)
        {
            byte[] output;
            try
            {
                output = run(doc.Bytes);
            }
            catch (Exception ex)
            {
                failures.Append(operation).Append(" threw ").Append(ex.GetType().Name)
                    .Append(": ").Append(ex.Message).Append(Environment.NewLine);
                continue;
            }

            var report = ExportValidator.Validate(output);
            if (!report.IsValid)
                failures.Append(operation).Append(" produced ").Append(report.ErrorCount)
                    .Append(" validation error(s):").Append(Environment.NewLine)
                    .Append(report.ToLogText()).Append(Environment.NewLine);
        }

        Assert.True(failures.Length == 0,
            $"Operations over well-formed fixture '{doc.Name}' damaged the document:"
            + Environment.NewLine + failures);
    }

    /// <summary>
    /// A malformed fixture must still be <em>handled</em>: refused with a recoverable exception or
    /// processed, never escaping as a defect-class crash. #54 enforces this across a mutation
    /// corpus; here it guards the specific awkward documents this suite records.
    /// </summary>
    [Theory]
    [MemberData(nameof(CorpusNames))]
    public void Operations_OverMalformedCorpus_FailHandled(string name)
    {
        var doc = Doc(name);
        if (doc.WellFormed) return;

        foreach (var (operation, run) in GoldenCorpus.Operations)
        {
            try
            {
                run(doc.Bytes);
            }
            catch (Exception ex) when (ex is InvalidDataException or ArgumentException
                                           or PdfEditor.Core.Pdf.PdfFormatException)
            {
                Assert.False(string.IsNullOrWhiteSpace(ex.Message),
                    $"'{doc.Name}'.{operation} threw {ex.GetType().Name} with no message.");
            }
        }
    }

    /// <summary>
    /// Every recorded golden must belong to a live corpus document. Without this, deleting a
    /// fixture leaves its recording behind and the suite quietly stops testing it while the file
    /// keeps suggesting otherwise.
    /// </summary>
    [Fact]
    public void EveryRecordedGolden_BelongsToACorpusDocument()
    {
        var recorded = Directory.Exists(GoldenFile.Directory)
            ? Directory.GetFiles(GoldenFile.Directory, "*.txt").Select(Path.GetFileNameWithoutExtension).ToList()
            : new List<string?>();
        var live = GoldenCorpus.Documents.Select(d => d.Name).ToHashSet(StringComparer.Ordinal);

        Assert.All(recorded, name => Assert.True(live.Contains(name!),
            $"{name}.txt has no corpus document. Delete the recording or restore the fixture."));
        Assert.Equal(live.Count, recorded.Count);
    }

    /// <summary>
    /// The hand-written fixtures are pinned by hash. If this moves without the corpus being
    /// deliberately edited, something nondeterministic has crept into a generator and every
    /// golden built from it would start drifting.
    /// </summary>
    [Fact]
    public void Corpus_IsBitForBitReproducible()
    {
        const string expected = "C84099E971C41B9192CE49A720D5C5689591CDC3383A87076581AD26550A5F6F";
        using var sha = SHA256.Create();
        foreach (var doc in GoldenCorpus.Documents.Where(d => d.Reproducible))
        {
            byte[] name = Encoding.UTF8.GetBytes(doc.Name);
            sha.TransformBlock(name, 0, name.Length, null, 0);
            sha.TransformBlock(doc.Bytes, 0, doc.Bytes.Length, null, 0);
        }
        sha.TransformFinalBlock(Array.Empty<byte>(), 0, 0);
        string actual = Convert.ToHexString(sha.Hash!);

        Assert.True(expected == actual,
            $"The pinned corpus hash changed: expected {expected}, got {actual}. If you edited a "
            + "fixture on purpose, update the constant (and expect the goldens to move with it). "
            + "If you did not, a generator has stopped being deterministic.");
    }

    /// <summary>Names are the golden filenames; a duplicate would silently overwrite a recording.</summary>
    [Fact]
    public void CorpusNames_AreUniqueAndFilenameSafe()
    {
        var names = GoldenCorpus.Documents.Select(d => d.Name).ToList();
        Assert.Equal(names.Count, names.Distinct(StringComparer.Ordinal).Count());
        Assert.All(names, n => Assert.Matches("^[a-z0-9-]+$", n));
        Assert.NotEmpty(GoldenCorpus.Operations);
    }

    /// <summary>
    /// The corpus has to actually contain the things issue #53 names, and a reviewer should not
    /// have to take that on trust. Asserting on the recordings rather than on the generators means
    /// a fixture that stops exercising its feature (a <c>/ToUnicode</c> dropped from a builder,
    /// say) fails here as well as diffing the golden.
    /// </summary>
    [Fact]
    public void Corpus_CoversTheFeaturesTheIssueNames()
    {
        string all = string.Join('\n', GoldenCorpus.Documents.Select(d =>
            GoldenProjection.Describe(d.Bytes)));

        Assert.Contains("subtype=Type3", all, StringComparison.Ordinal);          // complex fonts
        Assert.Contains("subtype=Type0", all, StringComparison.Ordinal);
        Assert.Contains("encoding=Identity-H", all, StringComparison.Ordinal);
        Assert.Contains("+Differences[", all, StringComparison.Ordinal);
        Assert.Contains("toUnicode=yes", all, StringComparison.Ordinal);
        Assert.Contains("charProcs=", all, StringComparison.Ordinal);

        Assert.Contains("SMask=", all, StringComparison.Ordinal);                 // transparency
        Assert.Contains("smask=yes", all, StringComparison.Ordinal);
        Assert.Contains("BM=/Multiply", all, StringComparison.Ordinal);
        Assert.Contains("Transparency(cs=/DeviceRGB I=true K=true)", all, StringComparison.Ordinal);

        Assert.Contains("      xobject Fm3", all, StringComparison.Ordinal);      // nested XObjects
        Assert.Contains("validation: ", all, StringComparison.Ordinal);           // malformed streams
        Assert.Contains("Error/PDF0", all, StringComparison.Ordinal);
    }

    /// <summary>
    /// A yardstick, not a benchmark: the sibling fuzz suite runs in about 13 seconds and this one
    /// should stay in the same class. If the corpus or the operation list grows past that, split
    /// the deeper part behind a trait rather than making every CI run wait for it.
    /// </summary>
    [Fact]
    public void WholeSuite_StaysWithinItsTimeBudget()
    {
        var clock = System.Diagnostics.Stopwatch.StartNew();
        foreach (var doc in GoldenCorpus.Documents)
        {
            _ = GoldenProjection.Describe(doc.Bytes);
            foreach (var (operation, run) in GoldenCorpus.Operations)
                _ = GoldenProjection.DescribeOperation(operation, () => run(doc.Bytes));
        }
        clock.Stop();

        Assert.True(clock.Elapsed < TimeSpan.FromSeconds(60),
            string.Create(CultureInfo.InvariantCulture,
                $"A full corpus pass took {clock.Elapsed.TotalSeconds:F1}s, over the 60s budget."));
    }
}
