'use strict';

/**
 * Small image files for the import and merge tests, one per format the viewer opens. Each was
 * written by ImageMagick, not by anything under test, and is embedded here so the suite needs no
 * image tooling to run.
 */

/** An 8x8 baseline JPEG, colour (0, 128, 255). */
const JPEG = Buffer.from(
  '/9j/4AAQSkZJRgABAQAAAAAAAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQ' +
  'ERMUFRUVDA8XGBYUGBIUFRT/2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU' +
  'FBQUFBQUFBQUFBQUFBT/wAARCAAIAAgDAREAAhEBAxEB/8QAFAABAAAAAAAAAAAAAAAAAAAAB//EABQQAQAAAAAAAAAAAAAA' +
  'AAAAAAD/xAAUAQEAAAAAAAAAAAAAAAAAAAAI/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8APzjDp//Z',
  'base64');

/** An 8x8 RGB PNG with no alpha channel, colour (0, 128, 255). */
const PNG_OPAQUE = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAIAAABLbSncAAAAFUlEQVQI12NkaPjPgA0wMeAAg1MCAC5SAY8ZqPAZAAAAAElF' +
  'TkSuQmCC',
  'base64');

/** An 8x8 RGBA PNG, red at 50% opacity. */
const PNG_ALPHA = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAFklEQVQY02P8z8BQz4AHMDEQAMNDAQCQTAGO+vj6XAAAAABJ' +
  'RU5ErkJggg==',
  'base64');

/** An 8x8 GIF, colour (0, 128, 255). */
const GIF = Buffer.from(
  'R0lGODlhCAAIAPAAAACA/wAAACH5BAAAAAAAIf8LSW1hZ2VNYWdpY2sOZ2FtbWE9MC40NTQ1NDUALAAAAAAIAAgAAAIHhI+p' +
  'y+1dAAA7',
  'base64');

/** An 8x8 24-bit BMP, colour (0, 128, 255). */
const BMP = Buffer.from(
  'Qk32AAAAAAAAADYAAAAoAAAACAAAAAgAAAABABgAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAA/4AA/4AA/4AA/4AA/4AA/4AA' +
  '/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA' +
  '/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA' +
  '/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA/4AA',
  'base64');

/** An 8x8 lossy WebP, colour (0, 128, 255). */
const WEBP = Buffer.from(
  'UklGRjwAAABXRUJQVlA4IDAAAAAQAgCdASoIAAgAAgA0JaACdLoB+AH4AAPIAP7qZf/9pZCFdf9Br/69Dhdlfh4AAAA=',
  'base64');

/** A two-page uncompressed 8-bit RGB TIFF: red, then blue. */
const TIFF_TWO_PAGES = Buffer.from(
  'SUkqAMgAAAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/' +
  'AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/' +
  'AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAAQAP4ABAABAAAAAgAAAAAB' +
  'AwABAAAACAAAAAEBAwABAAAACAAAAAIBAwADAAAAjgEAAAMBAwABAAAAAQAAAAYBAwABAAAAAgAAAAoBAwABAAAAAQAAABEB' +
  'BAABAAAACAAAABIBAwABAAAAAQAAABUBAwABAAAAAwAAABYBAwABAAAACAAAABcBBAABAAAAwAAAABwBAwABAAAAAQAAACkB' +
  'AwACAAAAAAACAD4BBQACAAAAxAEAAD8BBQAGAAAAlAEAAJQCAAAIAAgACACF61EAAACAAMP1qAAAAAACzcxMAAAAAAHNzEwA' +
  'AACAAM3MTAAAAAACj8L1AAAAABA3GqAAAAAAAiuHCgAAACAAAAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/' +
  'AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/' +
  'AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/AAD/' +
  'AAD/AAD/AAD/AAD/EAD+AAQAAQAAAAIAAAAAAQMAAQAAAAgAAAABAQMAAQAAAAgAAAACAQMAAwAAAFoDAAADAQMAAQAAAAEA' +
  'AAAGAQMAAQAAAAIAAAAKAQMAAQAAAAEAAAARAQQAAQAAANQBAAASAQMAAQAAAAEAAAAVAQMAAQAAAAMAAAAWAQMAAQAAAAgA' +
  'AAAXAQQAAQAAAMAAAAAcAQMAAQAAAAEAAAApAQMAAgAAAAEAAgA+AQUAAgAAAJADAAA/AQUABgAAAGADAAAAAAAACAAIAAgA' +
  'hetRAAAAgADD9agAAAAAAs3MTAAAAAABzcxMAAAAgADNzEwAAAAAAo/C9QAAAAAQNxqgAAAAAAIrhwoAAAAgAA==',
  'base64');

/** A one-page LZW-compressed 8-bit RGB TIFF, colour (0, 160, 0). */
const TIFF_LZW = Buffer.from(
  'SUkqAC4AAACAABQACCQWDQeEQSBwmGQmFw2IQqIxOHxOGRWLQiMRmDRuOACAgBAAAAEDAAEAAAAIAAAAAQEDAAEAAAAIAAAA' +
  'AgEDAAMAAAD0AAAAAwEDAAEAAAAFAAAABgEDAAEAAAACAAAACgEDAAEAAAABAAAAEQEEAAEAAAAIAAAAEgEDAAEAAAABAAAA' +
  'FQEDAAEAAAADAAAAFgEDAAEAAAAIAAAAFwEEAAEAAAAmAAAAHAEDAAEAAAABAAAAKQEDAAIAAAAAAAEAPQEDAAEAAAACAAAA' +
  'PgEFAAIAAAAqAQAAPwEFAAYAAAD6AAAAAAAAAAgACAAIAIXrUQAAAIAAw/WoAAAAAALNzEwAAAAAAc3MTAAAAIAAzcxMAAAA' +
  'AAKPwvUAAAAAEDcaoAAAAAACK4cKAAAAIAA=',
  'base64');

/**
 * A 1200x300 black-and-white PNG of the words "INVOICE 4471" and nothing else: a scan, with the
 * text only in its pixels, for the OCR tests.
 */
const SCAN_PNG = Buffer.from(
  'iVBORw0KGgoAAAANSUhEUgAABLAAAAEsAQAAAAD7xnf9AAAEcElEQVR42u3aTZKbOBgGYDFUhVlMhZxguMIsZzXMsWaRCsrN' +
  'dBSOoCULCvL9yG1w24pTieSvpt63u2waMHpayDJIdrvJuFcDwAILLLDAAstIwAILLAsBCyywLAQssMCyELDAAstCwAILLAsB' +
  'CyywLAQssMCyELDAAstCwAILLAsBCyywLAQssMCyELDAAstCwAILLAsBCyywLAQssMCyELDAAstCwAILLAsBCyywLAQssMCy' +
  'ELD+7yw3XBf717DisMeWnj39UNaOVrmGlhYGRUc7Lo4y6e5Loy8f95XXDvLKEqx+j42s8FzyQsQgiKXjIrlkYY1pd2FtB1a8' +
  'iH85yymLS2aMFsdLGy12edbmCrNCYq1iERaDmhNrFtZ6Zc0FWdMbK2rltMqKXPSJFYS1VGTNw+XPj9zmmTVLY8+wxqKs8cii' +
  '88SnlVmBz+CJ5YUVa7PoIXDzmoTl+Q0wyXvy8jphzUnpy7IGXkFLwvKD9EvynqTFcGL9pqx/E2va585XYIWBSUwjzMYVEY+s' +
  'TVnhwNrLsXphcelhFEvolUVr1iNr/SAsH8brUQqzlguLnmZhrWzYTqyPwvpahfV798byo1i4++ouH4AH1qKsRllbDdYqn9jT' +
  'kdXesuKfUoFtYjVFWX+0B5ZY6IEwsXvH+kdYXW2W27OsWVhrYq1lWdxgnP7vqYmtyupvWeGLXoolVluJtaV+guqBMPNrWb0T' +
  'lpPWIlW0KWu4ZXmp0jgoSzeUY9GRRfZd1ldljZVZdFrkzG3SxsI7ViOsObFiYRaV4uT432FtrbDClFh9Rdag25k13rI6Ze11' +
  'WERR1luDus9aleXTFt21NCuMD1hyRS9LvbCaSix6UFZ8yJKyl0FYbdoSqrAIxJfyGVYU1vbGGsuyiPAUax6ZtXa1Wfr7LMsX' +
  'ZlG/4PZUVTlWmJi19Kd6ej3Ly+d5HCqxqDBlUXG5fuuGpQcpzVJIjtUIax4rsehPZfksi3oGZoVJt2x1WNTC+H70eVZTmuWn' +
  'Z1jUMzDF79VYo7LcnmMtynKJtRZnhVEvTd2eu96iDotZzYXVlmbNw1MsJ4OWLo13VWNJrySsu9fyN6y0viBLbn52Z5TFpyVz' +
  'n3jDisVZS8cr/Oc0wvzgrvqW1ddkPR6DqM5aW2H91/0IKzW94qzwd5c6yUfjW5eeXfqt8qytuct6Nxp4YoVKrPmvPl0XPBo7' +
  'PbPG0qxdbgTnT8KaHo80v4Yl05a5cfkTy5dneV4RdTZ1yMxinFhTTVZ2zqcyKyiLSzvPkK3nGbIjS44RdVK0JGuRwrPziXdZ' +
  'bTHWfGVlZ18PrK0CS+arV7lJzc5VH1lNVVZ2Zr8ya1GWlpn5HsSBpdfMFVjpfjR9a6Tbj98aqcy6u3G4Lva/rMifZr0uYIEF' +
  'loWABRZYFgIWWGBZCFhggWUhYIEFloWABRZYFgIWWGBZCFhggWUhYIEFloWABRZYFgIWWGBZCFhggWUhYIEFloWABRZYFgIW' +
  'WGBZCFhggWUhYIEFloWABRZYFvINLgtuL2czdNkAAAAASUVORK5CYII=',
  'base64');

module.exports = { JPEG, PNG_OPAQUE, PNG_ALPHA, GIF, BMP, WEBP, TIFF_TWO_PAGES, TIFF_LZW, SCAN_PNG };
